# Generated by Django 3.2.5 on 2021-08-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0002_rename_firends_user_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['list_title']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='main_list',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='list_status',
        ),
    ]
