# Generated by Django 3.2.5 on 2021-08-03 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='main_list',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(blank=True, max_length=300)),
                ('list_status', models.BooleanField(default=False)),
                ('all_tasks', models.ManyToManyField(to='list_app.Task')),
                ('user_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['list_status'],
            },
        ),
    ]
