# Generated by Django 3.2.5 on 2021-08-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firends',
            new_name='friends',
        ),
    ]
