# Generated by Django 3.2.5 on 2021-08-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0002_auto_20210803_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='list_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
