# Generated by Django 3.2.5 on 2021-08-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0003_todolist_list_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
    ]
