# Generated by Django 3.2.5 on 2021-08-04 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_app.category'),
        ),
    ]
